version: '3.7'
services:
  order-service:
    image: order-server:latest
    ports:
      - "9001:9001"
    volumes:
      - /home/zycao/work/study-workspaces/study-springcloud/study-springcloud-server/study-springcloud-server-user
  user-service:
    image: user-server:latest
    ports:
      - "9000:9000"
    volumes:
      - /home/zycao/work/study-workspaces/study-springcloud/study-springcloud-server/study-springcloud-server-order

